# version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-backend
    network_mode: "host"
    environment:
      - TRANSFORMERS_CACHE=/app/local_models
      - TRANSFORMERS_OFFLINE=1
    volumes:
      - .:/app
    depends_on:
      - qdrant
    command: sh -c "npm install; node ingest.js; node server.js"
#    command: sh -c "node server.js"
#    command: sh -c "tail -f /dev/null"

volumes:
  qdrant_storage:
